// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'

// @ts-ignore
import { resolve } from '@decentralized-identity/ion-tools';

const key = "did:ion:EiDZDySgnNA4F93KMQQw1_0lcpI0lS9FhjJ7sG6SXFWtMA:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJrZXktMSIsInB1YmxpY0tleUp3ayI6eyJjcnYiOiJzZWNwMjU2azEiLCJrdHkiOiJFQyIsIngiOiItb01SOUxWc01pU3ZxYXJxVVF6bVR2Sm1uVUREbkpkZVAzVlJ0Y1Qyd0tNIiwieSI6ImRiSXBFb0tPal9wZWd2ajEtM3I2RmtnSFBWU0hCQXlxTjB6NXphSlJUbkUifSwicHVycG9zZXMiOlsiYXV0aGVudGljYXRpb24iXSwidHlwZSI6IkVjZHNhU2VjcDI1NmsxVmVyaWZpY2F0aW9uS2V5MjAxOSJ9XSwic2VydmljZXMiOlt7ImlkIjoiZG9tYWluLTEiLCJzZXJ2aWNlRW5kcG9pbnQiOiJodHRwczovL2dldHBvcnRhYmwuY29tIiwidHlwZSI6IkxpbmtlZERvbWFpbnMifV19fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaURkWnd6eFNoNkRUTWJ1MnQxRlVRaFNXRTNESVhIWUQyX3dRSmZFdTV3Q0ZRIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlEWnJxZjBlQ2JwTS1EM1dvWjd6dzZoMHlYYWxhN2ZrSzIxS2JhZkdoR19QUSIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpREM0d3NEQ2NIYVNFdVBxRlJJVHJqakVxM1hQYXAzTi1pQkdNXzgwOFJpa2cifX0";
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {

  const result: any = await resolve(key)
  result.didDocument.verificationMethod[0].publicKey
  res.status(200).send(JSON.stringify(result, null, 2))
}
// eyJrdHkiOiJFQyIsImNydiI6InNlY3AyNTZrMSIsIngiOiItb01SOUxWc01pU3ZxYXJxVVF6bVR2Sm1uVUREbkpkZVAzVlJ0Y1Qyd0tNIiwieSI6ImRiSXBFb0tPal9wZWd2ajEtM3I2RmtnSFBWU0hCQXlxTjB6NXphSlJUbkUiLCJkIjoicUNFSzE1X1NJSU9NbFZaQjd1OXVrNE1Sb09qWmhNSTg5V21aQ25td0IwcyJ9